name = "test-function-build-oidc"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "test-function-build-oidc_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "test-function-build-oidc.wasm"
command = "npm run build:release"
